## Config

In [1]:
import pickle, os
import pandas as pd, numpy as np
from collections import defaultdict

DATE       = '07262026'
CJ_DE = 'Important_genes/CJ_cleaned_sssubclass_v4_or_hypobkgd_sigupdate_07262026/CJ_cleaned_sssubclass_v4_or_hypobkgd_sigupdate_07262026.pkl'
AC_DE = 'Important_genes/AC_cleaned_sssubclass_v4_or_hypobkgd_sigupdate_07262026/AC_cleaned_sssubclass_v4_or_hypobkgd_sigupdate_07262026.pkl'
XT_DE = 'Important_genes/XT_cleaned_sssubclass_v4_or_hypobkgd_sigupdate_07262026/XT_cleaned_sssubclass_v4_or_hypobkgd_sigupdate_07262026.pkl'
DR_DE = 'Important_genes/DR_cleaned_sssubclass_v4_or_hypobkgd_sigupdate_07262026/DR_cleaned_sssubclass_v4_or_hypobkgd_sigupdate_07262026.pkl'
DE_PATH = {'CJ':CJ_DE,'AC':AC_DE,'XT':XT_DE,'DR':DR_DE}
OTO_PATH   = 'OTO_star_nothreshold_missing_le2_expressionthresh_07262026.tsv'
TF_PATH    = 'Fin_TF_06012026.csv'

SPECIES    = ['CJ', 'AC', 'XT', 'DR']   # non-mammal species: DE files + OTO columns

# --- conservation stringency knob -------------------------------------------------
# A TF is "conserved" in a group when it is DE in at least `required(group_size)`
# member species. Set MIN_SPECIES to one of:
#   'all'                -> DE in every member          (2/3/4 -> 2/3/4, strict)
#    N   (int)           -> DE in >= N members          (groups with < N members lack)
#   {2: 2, 3: 3, 4: 3}   -> explicit bar per group size (this gives 2/3/3: a
#                           4-species group needs only 3 of its 4 members)
# Shortcut for a "cap at K" rule: {n: min(n, K) for n in (2, 3, 4)}  (K=3 -> 2/3/3).
MIN_SPECIES = {2: 2, 3: 3, 4: 4}


def required(n_members):
    """How many member species a TF must be DE in for this group size."""
    if MIN_SPECIES == 'all':
        return n_members
    if isinstance(MIN_SPECIES, dict):
        return MIN_SPECIES[n_members]
    return int(MIN_SPECIES)

## 1. Load DE gene sets

One dict per species: `{subclass label -> set of DE gene symbols}`. Symbols are kept in native
casing (CJ upper, ac/xt/dr lower) so they line up with the OTO species columns.

In [2]:
de = {}
for S in SPECIES:
    spkl = DE_PATH[S]
    with open(spkl, 'rb') as fh:
        raw = pickle.load(fh)
    de[S] = {k: set(v) for k, v in raw.items()}
    print(f'{S}: {len(de[S])} subclasses, '
          f'{sum(len(v) for v in de[S].values())} DE gene calls')

CJ: 81 subclasses, 21208 DE gene calls
AC: 73 subclasses, 18319 DE gene calls
XT: 83 subclasses, 17626 DE gene calls
DR: 38 subclasses, 28554 DE gene calls

## 2. Shared subclasses

The member species are the `cj/ac/xt/dr` tokens in the label. A subclass is shared if it names
>=2 species and is present in each of those species' DE dict (asserted). Mouse-merged tokens
(`m066`) and Allen labels never match, so single-species and pass-through types drop out.

In [3]:
def participants(label):
    toks = set(label.split('_'))
    return [p.upper() for p in ['cj', 'ac', 'xt', 'dr'] if p in toks]


shared = {}
for S in SPECIES:
    for label in de[S]:
        pit = participants(label)
        if len(pit) >= 2:
            shared[label] = pit

for label, pit in shared.items():
    missing = [S for S in pit if label not in de[S]]
    assert not missing, f'{label}: named {pit} but absent from {missing}'

print(f'{len(shared)} shared subclasses')
for label, pit in sorted(shared.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    print(f'  {label:<16} {pit}')

21 shared subclasses
  cj_ac_xt_dr_1    ['CJ', 'AC', 'XT', 'DR']
  cj_ac_xt_dr_2    ['CJ', 'AC', 'XT', 'DR']
  cj_ac_xt_dr_3    ['CJ', 'AC', 'XT', 'DR']
  cj_ac_xt_dr_4    ['CJ', 'AC', 'XT', 'DR']
  cj_ac_xt_dr_5    ['CJ', 'AC', 'XT', 'DR']
  ac_xt_dr_1       ['AC', 'XT', 'DR']
  cj_ac_xt_1       ['CJ', 'AC', 'XT']
  cj_xt_dr_1       ['CJ', 'XT', 'DR']
  cj_xt_dr_2       ['CJ', 'XT', 'DR']
  ac_dr_1          ['AC', 'DR']
  ac_dr_2          ['AC', 'DR']
  ac_xt_1          ['AC', 'XT']
  ac_xt_2          ['AC', 'XT']
  ac_xt_3          ['AC', 'XT']
  ac_xt_4          ['AC', 'XT']
  cj_ac_1          ['CJ', 'AC']
  cj_ac_2          ['CJ', 'AC']
  cj_ac_3          ['CJ', 'AC']
  cj_ac_4          ['CJ', 'AC']
  cj_xt_1          ['CJ', 'XT']
  xt_dr_1          ['XT', 'DR']

## 3. Orthogroups and TF orthogroups

Orthogroups are identified by their **mouse (`MM`) symbol** — unique and non-null in this OTO
table, so it's a safe one-to-one id. `gene2og[S]` maps a native symbol to the orthogroup
(mouse-name) it sits in; `tf_ogs` are the orthogroups whose mouse name is in the TF list; and
`og_present[S]` records which orthogroups actually have a gene in species `S`. Since each `og`
id already *is* the mouse TF name, it's used directly as the TF label downstream.

In [4]:
# Orthogroups are keyed by their MOUSE (MM) symbol. MM is unique and non-null in this
# OTO table (verified), so the mouse name is a safe one-to-one id for each orthogroup.
oto = pd.read_csv(OTO_PATH, sep='\t', index_col='MM')

# native symbol -> set of orthogroup (mouse-name) ids it sits in, per species
gene2og = {S: defaultdict(set) for S in SPECIES}
for og, row in oto.iterrows():
    for S in SPECIES:
        g = row[S]
        if isinstance(g, str):
            gene2og[S][g].add(og)

# orthogroups that actually have a gene in species S
og_present = {S: set(oto.index[oto[S].notna()]) for S in SPECIES}

# TF orthogroups: mouse names in the TF list. The og id *is* the mouse TF name.
TF_set = set(pd.read_csv(TF_PATH)['0'].dropna().astype(str))
tf_ogs = set(oto.index) & TF_set

print(f'{len(TF_set)} TF symbols -> {len(tf_ogs)} TF orthogroups in OTO '
      f'(of {len(oto)} orthogroups total)')

1256 TF symbols -> 857 TF orthogroups in OTO (of 14485 orthogroups total)

## 4. DE TF orthogroups per (species, subclass)

For a member species, intersect its DE genes for the subclass with the TF orthogroups.

In [5]:
def de_tf_ogs(S, label):
    return {og
            for g in de[S].get(label, ())
            for og in gene2og[S].get(g, ())
            if og in tf_ogs}

## 5. Conserved-TF long table

One row per (subclass, TF orthogroup) that is DE in at least one member species. `n_required` is
the `MIN_SPECIES` bar for that group size and `conserved` is `n_DE >= n_required`. For the rest,
`present_not_DE` vs `ortholog_absent` says whether a miss is biological or just a missing
ortholog. Re-run this cell (and the ones below) after changing `MIN_SPECIES` in Config.

In [6]:
rows = []
for label, pit in sorted(shared.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    per = {S: de_tf_ogs(S, label) for S in pit}
    req = required(len(pit))
    for og in sorted(set().union(*per.values())):
        de_in   = [S for S in pit if og in per[S]]
        not_de  = [S for S in pit if og not in per[S] and og in og_present[S]]
        absent  = [S for S in pit if og not in og_present[S]]
        rows.append({
            'subclass'           : label,
            'n_species_in_group' : len(pit),
            'group_species'      : ','.join(pit),
            'TF'                 : og,          # og id is the mouse TF name
            'n_DE'               : len(de_in),
            'n_required'         : req,
            'DE_in'              : ','.join(de_in),
            'present_not_DE'     : ','.join(not_de),
            'ortholog_absent'    : ','.join(absent),
            'conserved'          : len(de_in) >= req,
        })

tf_long = pd.DataFrame(rows)
print(f'{tf_long.shape[0]} (subclass, TF) rows | '
      f'{int(tf_long["conserved"].sum())} conserved at MIN_SPECIES={MIN_SPECIES!r}')
tf_long.head(20)

1216 (subclass, TF) rows | 130 conserved at MIN_SPECIES={2: 2, 3: 3, 4: 4}

,subclass,n_species_in_group,group_species,TF,n_DE,n_required,DE_in,present_not_DE,ortholog_absent,conserved
0,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Arntl,1,4,DR,"CJ,AC,XT",,False
1,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Bach1,1,4,DR,"CJ,AC,XT",,False
2,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Bach2,1,4,DR,"CJ,AC,XT",,False
3,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Barhl1,3,4,"CJ,AC,XT",DR,,False
4,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Barhl2,2,4,"CJ,AC","XT,DR",,False
5,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Bcl11a,1,4,DR,"CJ,AC,XT",,False
6,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Bcl11b,3,4,"CJ,XT,DR",AC,,False
7,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Bhlhe22,1,4,DR,"AC,XT",CJ,False
8,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Bhlhe23,1,4,DR,"CJ,AC,XT",,False
9,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Bhlhe40,1,4,DR,"CJ,AC,XT",,False
10,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Bnc2,3,4,"CJ,AC,XT",DR,,False
11,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Carf,1,4,DR,"CJ,XT",AC,False
12,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Cdc5l,1,4,DR,"CJ,AC,XT",,False
13,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Creb1,1,4,DR,"CJ,AC,XT",,False
14,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Crebrf,1,4,DR,"CJ,AC,XT",,False
15,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Dmrta2,1,4,DR,"CJ,AC,XT",,False
16,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",E2f6,1,4,DR,"CJ,AC,XT",,False
17,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Ebf1,4,4,"CJ,AC,XT,DR",,,True
18,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Ebf2,4,4,"CJ,AC,XT,DR",,,True
19,cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",Ebf3,4,4,"CJ,AC,XT,DR",,,True

## 6. Per-subclass summary

Every shared subclass appears here (including those with zero DE TFs), sorted so the widest
groups and the most TF-poor come first.

Each entry in `conserved_TFs` is tagged with any member species the TF is **not** DE in — which
happens under a relaxed `MIN_SPECIES` (e.g. 2/3/3, where a 4-species group can be conserved on 3
of 4). `Lhx2(-DR)` means conserved but not DE in zebrafish; a trailing `*` (e.g. `Nfib(-DR*)`)
means DR lacks the ortholog entirely, so it could never have been DE. Untagged names are DE in
every member.

In [8]:
meta = pd.DataFrame(
    [{'subclass': l, 'n_species_in_group': len(p), 'group_species': ','.join(p)}
     for l, p in shared.items()]).set_index('subclass')

cons = tf_long[tf_long['conserved']].copy()


def _tf_label(row):
    """TF name, tagged with any member species it is NOT DE in (relaxed threshold).
    A trailing '*' marks species where the ortholog is absent (can't be DE) rather
    than merely not called DE."""
    absent = [s for s in row['ortholog_absent'].split(',') if s]
    not_de = [s for s in row['present_not_DE'].split(',') if s]
    missing = [f'{s}*' for s in absent] + not_de
    return row['TF'] if not missing else f"{row['TF']}(-{'/'.join(missing)})"


cons['tf_label'] = cons.apply(_tf_label, axis=1)

n_union = tf_long.groupby('subclass')['TF'].nunique().rename('n_TF_union')
n_cons  = cons.groupby('subclass')['TF'].nunique().rename('n_TF_conserved')
names   = (cons.dropna(subset=['TF']).groupby('subclass')['tf_label']
               .apply(lambda s: ', '.join(sorted(s.unique())))
               .rename('conserved_TFs'))

per_subclass = meta.join(n_union).join(n_cons).join(names)
per_subclass['n_TF_union']     = per_subclass['n_TF_union'].fillna(0).astype(int)
per_subclass['n_TF_conserved'] = per_subclass['n_TF_conserved'].fillna(0).astype(int)
per_subclass['conserved_TFs']  = per_subclass['conserved_TFs'].fillna('')
per_subclass = per_subclass.sort_values(['n_species_in_group', 'n_TF_conserved'],
                                        ascending=[False, True])

# conserved_TFs tags: 'Lhx2(-DR)' = conserved but not DE in DR; '*' = ortholog absent there.
pd.set_option('display.max_colwidth', 200)
per_subclass

,n_species_in_group,group_species,n_TF_union,n_TF_conserved,conserved_TFs
subclass,,,,,
cj_ac_xt_dr_5,4,"CJ,AC,XT,DR",60,0,
cj_ac_xt_dr_2,4,"CJ,AC,XT,DR",76,1,Mef2c
cj_ac_xt_dr_3,4,"CJ,AC,XT,DR",55,2,"Lhx2, Lhx9"
cj_ac_xt_dr_4,4,"CJ,AC,XT,DR",66,2,"Gata3, Tal1"
cj_ac_xt_dr_1,4,"CJ,AC,XT,DR",159,6,"Ebf1, Ebf2, Ebf3, Irx1, Irx2, Lef1"
ac_xt_dr_1,3,"AC,XT,DR",27,0,
cj_ac_xt_1,3,"CJ,AC,XT",43,4,"Ebf1, Pitx2, Sim1, Uncx"
cj_xt_dr_2,3,"CJ,XT,DR",49,4,"Prdm16, Zic1, Zic2, Zic4"
cj_xt_dr_1,3,"CJ,XT,DR",145,10,"Dach1, Dach2, Lef1, Nr2e1, Prdm13, Prox1, Sox1, Sp5, St18, Zfp536"
ac_dr_2,2,"AC,DR",38,0,
xt_dr_1,2,"XT,DR",75,0,
cj_xt_1,2,"CJ,XT",29,1,Foxp2
ac_xt_3,2,"AC,XT",20,3,"Casz1, Esrrg, Nfia"
cj_ac_1,2,"CJ,AC",24,6,"Bcl11b, Dach1, Dach2, Meis2, Nr2f2, Tshz2"
ac_xt_4,2,"AC,XT",43,8,"Bcl11b, Bhlhe22, Foxg1, Nfia, Nfix, Tcf4, Zbtb16, Zeb2"
ac_xt_2,2,"AC,XT",66,9,"Dach1, Insm1, Nr2e1, Prdm13, Sox3, St18, Zfp516, Zfp536, Zic1"
cj_ac_2,2,"CJ,AC",46,11,"Lhx9, Nr3c2, Prox1, Rora, Sox13, Tcf7l2, Zbtb7c, Zfp521, Zic1, Zic2, Zic5"
ac_xt_1,2,"AC,XT",45,11,"Bsx, Dach2, Esr1, Hmx2, Hmx3, Lef1, Nkx2-1, Prdm13, Rara, Tbx2, Tbx3"
ac_dr_1,2,"AC,DR",62,14,"Bhlhe22, Ebf1, Ebf3, Id2, Neurod2, Neurod6, Nfia, Nfix, Pitx2, Satb1, Tcf4, Zbtb18, Zfp536, Zfpm2"
cj_ac_3,2,"CJ,AC",46,19,"Bcl11b, Emx2, Gata2, Gata3, Irx3, Lef1, Npas3, Otx2, Pax7, Rora, Sox14, Sox21, Tcf7, Tfap2a, Tfap2b, Tfap2e, Uncx, Zeb2, Zfpm1"
cj_ac_4,2,"CJ,AC",42,19,"Barhl2, Bcl11b, Ebf1, Ebf2, Ebf3, Lef1, Lhx2, Lhx9, Rarb, Rora, Rorb, Sox6, Tcf7, Tfap2a, Tfap2b, Tfap2d, Tfap2e, Tshz3, Zeb2"

In [9]:
per_subclass.index

Index(['cj_ac_xt_dr_5', 'cj_ac_xt_dr_2', 'cj_ac_xt_dr_3', 'cj_ac_xt_dr_4',
       'cj_ac_xt_dr_1', 'ac_xt_dr_1', 'cj_ac_xt_1', 'cj_xt_dr_2', 'cj_xt_dr_1',
       'ac_dr_2', 'xt_dr_1', 'cj_xt_1', 'ac_xt_3', 'cj_ac_1', 'ac_xt_4',
       'ac_xt_2', 'cj_ac_2', 'ac_xt_1', 'ac_dr_1', 'cj_ac_3', 'cj_ac_4'],
      dtype='object', name='subclass')

## 7. Save

In [10]:
if MIN_SPECIES == 'all':
    tag = 'all'
elif isinstance(MIN_SPECIES, dict):
    tag = 'req' + ''.join(str(MIN_SPECIES[k]) for k in sorted(MIN_SPECIES))  # e.g. req233
else:
    tag = f'min{int(MIN_SPECIES)}'

cons.sort_values(['n_species_in_group', 'subclass', 'TF'],
                 ascending=[False, True, True]).to_csv(
    f'nonmam_conserved_DE_TFs_{tag}_{DATE}.csv', index=False)
tf_long.to_csv(f'nonmam_subclass_TF_long_{tag}_{DATE}.csv', index=False)
per_subclass.to_csv(f'nonmam_subclass_TF_summary_{tag}_{DATE}.csv')
print('wrote:')
for f in (f'nonmam_conserved_DE_TFs_{tag}_{DATE}.csv',
          f'nonmam_subclass_TF_long_{tag}_{DATE}.csv',
          f'nonmam_subclass_TF_summary_{tag}_{DATE}.csv'):
    print('  ', f)

wrote:
   nonmam_conserved_DE_TFs_req234_07262026.csv
   nonmam_subclass_TF_long_req234_07262026.csv
   nonmam_subclass_TF_summary_req234_07262026.csv

In [12]:
for item in per_subclass.index:
    if per_subclass.loc[item,'n_TF_conserved'] < 2:
        print(item)

cj_ac_xt_dr_5
cj_ac_xt_dr_2
ac_xt_dr_1
ac_dr_2
xt_dr_1
cj_xt_1

## 8. Revert low-support mappings

Dissolve the shared subclasses that carry too few conserved DE TFs back to their original
per-species v4 labels. Reads the consensus column (`ss_subclass_nounlabeled_nmm_v4_nn`) and
writes a **cleaned** copy to a new column `ss_subclass_nounlabeled_nmm_cl_v4_nn`: for every cell
whose consensus label is in `REVERT_GROUPS`, the label is restored from
`ss_subclass_v4_nounlabeled_nn` (the node-level v4 label, e.g. `dr_5`); all other cells keep their
consensus label. The original consensus column is left untouched.

`REVERT_GROUPS` defaults to the six groups with **< 2 conserved TFs under the strict
`MIN_SPECIES='all'` criterion** — pinned explicitly rather than recomputed off the current
`MIN_SPECIES` (which would pick a different set).

The commit cell re-saves the four SAM h5ads (adding the new column) and is not reversible — the
first cell is a dry run; run the commit cell only once its report looks right.

In [11]:
import gc
from samalg import SAM

REVERT_LEVEL    = 'ss_subclass_v4_nounlabeled_nn'         # original per-species v4 node labels
CONSENSUS_LEVEL = 'ss_subclass_nounlabeled_nmm_v4_nn'     # consensus column from the mapping notebook (source, left intact)
OUTPUT_LEVEL    = 'ss_subclass_nounlabeled_nmm_cl_v4_nn'  # cleaned consensus written here (reverts applied)

SAM_DIR = 'Active_SAM_joined/'
H5AD = {
    'CJ': SAM_DIR + 'SAM_CJ_joined_v2_cleaned_03122025.h5ad',
    'AC': SAM_DIR + 'SAM_AC_ncbi_soupx_cleaned_03122025.h5ad',
    'XT': SAM_DIR + 'SAM_XT_joined_Slc17a6_cleaned_03122205.h5ad',
    'DR': SAM_DIR + 'SAM_DR_ncbi_joined_cleaned_07172026.h5ad',
}

# Groups to dissolve back to their v4 labels. Pinned explicitly: these are the shared
# subclasses with < 2 conserved TFs under the STRICT MIN_SPECIES='all' criterion.
REVERT_GROUPS = ['cj_ac_xt_dr_5', 'cj_ac_xt_dr_2', 'ac_xt_dr_1', 'ac_dr_2', 'cj_xt_1', 'xt_dr_1']

bad = [g for g in REVERT_GROUPS if g not in shared]
assert not bad, f'not shared subclasses: {bad}'


def revert_h5ad(S, fn, dry_run=True):
    sam = SAM()
    sam.load_data(fn)
    revert_obs_names = sam.adata.obs_names[sam.adata.obs[CONSENSUS_LEVEL].isin(REVERT_GROUPS)]
    obs = sam.adata.obs
    for col in (REVERT_LEVEL, CONSENSUS_LEVEL):
        if col not in obs.columns:
            raise KeyError(f'{S}: {col} missing from {fn}')
            
    fin_labels = []
    for item in sam.adata.obs_names:
        if item in revert_obs_names:
            fin_labels.append(sam.adata.obs.loc[item,REVERT_LEVEL])
        else:
            fin_labels.append(sam.adata.obs.loc[item,CONSENSUS_LEVEL])

    hit = obs.loc[revert_obs_names, CONSENSUS_LEVEL].value_counts().to_dict()
    print(f'{S}: {len(revert_obs_names)} cells reverted  {hit}')
    print(f'    {OUTPUT_LEVEL}: {obs[CONSENSUS_LEVEL].nunique()} -> {pd.Series(fin_labels).nunique()} distinct labels')

    if dry_run:
        print('    dry run — nothing written')
        return sam
    else:
        sam.adata.obs[OUTPUT_LEVEL] = fin_labels
        sam.save_anndata(fn)
        print(f'    saved {OUTPUT_LEVEL} into {fn}')
        return sam


# Dry run: report only, writes nothing.
for S in SPECIES:
    revert_h5ad(S, H5AD[S], dry_run=True)
    gc.collect()

/scratch/miniconda/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

CJ: 1171 cells reverted  {'cj_xt_1': 504, 'cj_ac_xt_dr_5': 348, 'cj_ac_xt_dr_2': 319, '004 L6 IT CTX Glut': 0, '325 CHOR NN': 0, '231 IPN-LDT Vsx2 Nkx6-1 Glut': 0, '235 PG-TRN-LRN Fat2 Glut': 0, '277 DTN-LDT-IPN Otp Pax3 Gaba': 0, '321 Astroependymal NN': 0, '322 Tanycyte NN': 0, '323 Ependymal NN': 0, '326 OPC NN': 0, '213 SCsg Gabrr2 Gaba': 0, '327 Oligo NN': 0, '329 ABC NN': 0, '330 VLMC NN': 0, '333 Endo NN': 0, '339 Astrocyte-like NN': 0, '215 SNc-VTA-RAmb Foxa1 Dopa': 0, '211 SC Tnnt1 Gli3 Gaba': 0, '212 SCs Lef1 Gli3 Gaba': 0, 'Unlabeled': 0, '209 SCs Pax7 Nfia Gaba': 0, '208 SC Lef1 Otx2 Gaba': 0, '207 SCs Dmbx1 Gaba': 0, '205 SC-PAG Lef1 Emx2 Gaba': 0, '203 LGv-SPFp-SPFm Nkx2-2 Tcf7l2 Gaba': 0, '202 PRT Tcf7l2 Gaba': 0, '190 ND-INC Foxd2 Glut': 0, '168 SPA-SPFm-SPFp-POL-PIL-PoT Sp9 Glut': 0, '164 APN C1ql4 Glut': 0, '159 IF-RL-CLI-PAG Foxa1 Glut': 0, '153 MG-POL-SGN Nts Glut': 0, '152 RE-Xi Nox4 Glut': 0, '340 Macrophage NN': 0, 'cj_14': 0, 'cj_13': 0, '006 L4/5 IT CTX Glut': 0, 'cj_xt_dr_1': 0, 'cj_m136_m138': 0, 'cj_m091_m099': 0, 'cj_m066_m067': 0, 'cj_ac_xt_dr_4': 0, 'cj_ac_xt_dr_3': 0, 'cj_ac_xt_dr_1': 0, 'cj_ac_xt_1': 0, 'cj_ac_4': 0, 'cj_ac_3': 0, 'cj_ac_2': 0, 'cj_ac_1': 0, 'cj_9': 0, 'cj_8': 0, 'cj_5': 0, 'cj_4': 0, 'cj_37': 0, 'cj_36': 0, 'cj_34': 0, 'cj_33': 0, 'cj_32': 0, 'cj_31': 0, 'cj_29': 0, 'cj_28': 0, 'cj_27': 0, 'cj_22': 0, 'cj_21': 0, 'cj_19': 0, 'cj_18': 0, '149 PVT-PT Ntrk1 Glut': 0, '145 MH Tac2 Glut': 0, '141 PH-SUM Foxa1 Glut': 0, '064 STR-PAL Chst9 Gaba': 0, '092 TMv-PMv Tbx3 Hist-Gaba': 0, '090 BST-MPN Six3 Nrgn Gaba': 0, '089 PVR Six3 Sox3 Gaba': 0, '088 BST Tac2 Gaba': 0, '086 MPO-ADP Lhx8 Gaba': 0, '085 SI-MPO-LPO Lhx8 Gaba': 0, '082 CEA-BST Ebf1 Pdyn Gaba': 0, '081 ACB-BST-FS D1 Gaba': 0, '076 MEA-BST Lhx6 Nfib Gaba': 0, '074 MEA-BST Lhx6 Sp9 Gaba': 0, '070 LSX Prdm12 Slit2 Gaba': 0, '069 LSX Nkx2-1 Gaba': 0, '068 LSX Otx2 Gaba': 0, '067 LSX Sall3 Pax6 Gaba': 0, '063 STR D1 Sema5a Gaba': 0, '094 SCH Six6 Cdc14a Gaba': 0, '062 STR D2 Gaba': 0, '061 STR D1 Gaba': 0, '058 PAL-STR Gaba-Chol': 0, '057 NDB-SI-MA-STRv Lhx8 Gaba': 0, '055 STR Lhx8 Gaba': 0, '054 STR Prox1 Lhx6 Gaba': 0, '053 Sst Gaba': 0, '052 Pvalb Gaba': 0, '049 Lamp5 Gaba': 0, '041 OB-in Frmd7 Gaba': 0, '017 CA3 Glut': 0, '014 LA-BLA-BMA-PA Glut': 0, '013 COAp Grxcr2 Glut': 0, '007 L2/3 IT CTX Glut': 0, '093 RT-ZI Gnb3 Gaba': 0, '097 PVHd-SBPV Six3 Prox1 Gaba': 0, '140 PMd-LHA Foxb1 Glut': 0, '123 DMH Nkx2-4 Glut': 0, '138 PH Pitx2 Glut': 0, '136 PMv-TMv Pitx2 Glut': 0, '135 STN-PSTN Pitx2 Glut': 0, '134 PH-ant-LHA Otp Bsx Glut': 0, '133 PVH-SO-PVa Otp Glut': 0, '132 AHN-RCH-LHA Otp Fezf1 Glut': 0, '131 LHA-AHN-PVH Otp Trh Glut': 0, '130 LHA Pmch Glut': 0, '129 VMH Nr5a1 Glut': 0, '128 VMH Fezf1 Glut': 0, '127 DMH-LHA Vgll2 Glut': 0, '126 ARH-PVp Tbx3 Glut': 0, '125 DMH Hmx2 Glut': 0, '124 MPN-MPO-PVpo Hmx2 Glut': 0, '122 LHA-MEA Otp Glut': 0, '098 AHN-SBPV-PVHd Pdrm12 Gaba': 0, '119 SI-MA-LPO-LHA Skor1 Glut': 0, '118 ADP-MPO Trp73 Glut': 0, '117 LHA Barhl2 Glut': 0, '116 AVPV-MEPO-SFO Tbr1 Glut': 0, '115 MS-SF Bsx Glut': 0, '111 TRS-BAC Sln Glut': 0, '109 LGv-ZI Otx2 Gaba': 0, '108 ARH-PVp Tbx3 Gaba': 0, '107 DMH Hmx2 Gaba': 0, '106 PVpo-VMPO-MPN Hmx2 Gaba': 0, '104 TU-ARH Otp Six6 Gaba': 0, '102 DMH-LHA Gsx1 Gaba': 0, '101 ZI Pax6 Gaba': 0, '100 AHN Onecut3 Gaba': 0, 'cj_xt_dr_2': 0}
    ss_subclass_nounlabeled_nmm_cl_v4_nn: 136 -> 137 distinct labels
    dry run — nothing written
AC: 1592 cells reverted  {'cj_ac_xt_dr_2': 561, 'cj_ac_xt_dr_5': 513, 'ac_dr_2': 398, 'ac_xt_dr_1': 120, '333 Endo NN': 0, '338 Lymphoid NN': 0, '330 VLMC NN': 0, '329 ABC NN': 0, '327 Oligo NN': 0, '231 IPN-LDT Vsx2 Nkx6-1 Glut': 0, '325 CHOR NN': 0, '324 Hypendymal NN': 0, '323 Ependymal NN': 0, '322 Tanycyte NN': 0, '321 Astroependymal NN': 0, '277 DTN-LDT-IPN Otp Pax3 Gaba': 0, '326 OPC NN': 0, '215 SNc-VTA-RAmb Foxa1 Dopa': 0, '216 MB-MY Tph2 Glut-Sero': 0, '340 Macrophage NN': 0, '214 IPN Otp Crisp1 Gaba': 0, '213 SCsg Gabrr2 Gaba': 0, '212 SCs Lef1 Gli3 Gaba': 0, '211 SC Tnnt1 Gli3 Gaba': 0, '209 SCs Pax7 Nfia Gaba': 0, '208 SC Lef1 Otx2 Gaba': 0, '205 SC-PAG Lef1 Emx2 Gaba': 0, '204 SC Otx2 Gcnt4 Gaba': 0, '203 LGv-SPFp-SPFm Nkx2-2 Tcf7l2 Gaba': 0, '200 PAG-ND-PCG Onecut1 Gaba': 0, '196 PAG-PPN Pax5 Sox21 Gaba': 0, '188 SCop Sln Glut': 0, '339 Astrocyte-like NN': 0, 'ac_14': 0, 'Unlabeled': 0, 'ac_m136_m138': 0, 'cj_ac_xt_dr_4': 0, 'cj_ac_xt_dr_3': 0, 'cj_ac_xt_dr_1': 0, 'cj_ac_xt_1': 0, 'cj_ac_4': 0, 'cj_ac_3': 0, 'cj_ac_2': 0, 'cj_ac_1': 0, 'ac_xt_4': 0, 'ac_xt_3': 0, 'ac_xt_2': 0, 'ac_xt_1': 0, 'ac_m124_m130': 0, '186 SCop Pou4f2 Neurod2 Glut': 0, 'ac_m058_m086': 0, 'ac_dr_1': 0, 'ac_35': 0, 'ac_32': 0, 'ac_31': 0, 'ac_29': 0, 'ac_28': 0, 'ac_26': 0, 'ac_25': 0, 'ac_2': 0, 'ac_19': 0, 'ac_18': 0, '187 SCsg Pde5a Glut': 0, '013 COAp Grxcr2 Glut': 0, '018 L2 IT PPP-APr Glut': 0, '070 LSX Prdm12 Slit2 Gaba': 0, '099 SBPV-PVa Six6 Satb2 Gaba': 0, '098 AHN-SBPV-PVHd Pdrm12 Gaba': 0, '097 PVHd-SBPV Six3 Prox1 Gaba': 0, '094 SCH Six6 Cdc14a Gaba': 0, '093 RT-ZI Gnb3 Gaba': 0, '092 TMv-PMv Tbx3 Hist-Gaba': 0, '089 PVR Six3 Sox3 Gaba': 0, '086 MPO-ADP Lhx8 Gaba': 0, '085 SI-MPO-LPO Lhx8 Gaba': 0, '079 CEA-BST Six3 Cyp26b1 Gaba': 0, '076 MEA-BST Lhx6 Nfib Gaba': 0, '074 MEA-BST Lhx6 Sp9 Gaba': 0, '073 MEA-BST Sox6 Gaba': 0, '069 LSX Nkx2-1 Gaba': 0, '101 ZI Pax6 Gaba': 0, '068 LSX Otx2 Gaba': 0, '067 LSX Sall3 Pax6 Gaba': 0, '064 STR-PAL Chst9 Gaba': 0, '062 STR D2 Gaba': 0, '061 STR D1 Gaba': 0, '058 PAL-STR Gaba-Chol': 0, '057 NDB-SI-MA-STRv Lhx8 Gaba': 0, '056 Sst Chodl Gaba': 0, '055 STR Lhx8 Gaba': 0, '054 STR Prox1 Lhx6 Gaba': 0, '047 Sncg Gaba': 0, '039 OB Meis2 Thsd7b Gaba': 0, '022 L5 ET CTX Glut': 0, '100 AHN Onecut3 Gaba': 0, '104 TU-ARH Otp Six6 Gaba': 0, '168 SPA-SPFm-SPFp-POL-PIL-PoT Sp9 Glut': 0, '129 VMH Nr5a1 Glut': 0, '152 RE-Xi Nox4 Glut': 0, '151 TH Prkcd Grin2c Glut': 0, '149 PVT-PT Ntrk1 Glut': 0, '142 HY Gnrh1 Glut': 0, '141 PH-SUM Foxa1 Glut': 0, '140 PMd-LHA Foxb1 Glut': 0, '136 PMv-TMv Pitx2 Glut': 0, '135 STN-PSTN Pitx2 Glut': 0, '134 PH-ant-LHA Otp Bsx Glut': 0, '133 PVH-SO-PVa Otp Glut': 0, '132 AHN-RCH-LHA Otp Fezf1 Glut': 0, '131 LHA-AHN-PVH Otp Trh Glut': 0, '130 LHA Pmch Glut': 0, '128 VMH Fezf1 Glut': 0, '106 PVpo-VMPO-MPN Hmx2 Gaba': 0, '127 DMH-LHA Vgll2 Glut': 0, '126 ARH-PVp Tbx3 Glut': 0, '125 DMH Hmx2 Glut': 0, '123 DMH Nkx2-4 Glut': 0, '122 LHA-MEA Otp Glut': 0, '119 SI-MA-LPO-LHA Skor1 Glut': 0, '118 ADP-MPO Trp73 Glut': 0, '117 LHA Barhl2 Glut': 0, '116 AVPV-MEPO-SFO Tbr1 Glut': 0, '115 MS-SF Bsx Glut': 0, '111 TRS-BAC Sln Glut': 0, '109 LGv-ZI Otx2 Gaba': 0, '107 DMH Hmx2 Gaba': 0, '175 SC Bnc2 Glut': 0}
    ss_subclass_nounlabeled_nmm_cl_v4_nn: 127 -> 127 distinct labels
    dry run — nothing written
XT: 1716 cells reverted  {'cj_ac_xt_dr_2': 813, 'xt_dr_1': 429, 'cj_xt_1': 217, 'cj_ac_xt_dr_5': 142, 'ac_xt_dr_1': 115, '330 VLMC NN': 0, 'cj_ac_xt_1': 0, 'ac_xt_4': 0, 'ac_xt_3': 0, 'ac_xt_2': 0, 'ac_xt_1': 0, 'Unlabeled': 0, '340 Macrophage NN': 0, '339 Astrocyte-like NN': 0, '338 Lymphoid NN': 0, '333 Endo NN': 0, '009 L2/3 IT PIR-ENTl Glut': 0, 'cj_ac_xt_dr_1': 0, '327 Oligo NN': 0, '326 OPC NN': 0, '322 Tanycyte NN': 0, '277 DTN-LDT-IPN Otp Pax3 Gaba': 0, '275 PDTg Otp Olig3 Gaba': 0, '262 Pineal Crx Glut': 0, '232 LDT Vsx2 Nkx6-1 Nfib Glut': 0, '231 IPN-LDT Vsx2 Nkx6-1 Glut': 0, '230 PRNr Otp Nfib Glut': 0, '216 MB-MY Tph2 Glut-Sero': 0, '215 SNc-VTA-RAmb Foxa1 Dopa': 0, '214 IPN Otp Crisp1 Gaba': 0, '209 SCs Pax7 Nfia Gaba': 0, '329 ABC NN': 0, 'cj_ac_xt_dr_3': 0, '011 L2 IT ENT-po Glut': 0, 'xt_25': 0, 'xt_8': 0, 'xt_7': 0, 'xt_42': 0, 'xt_41': 0, 'xt_40': 0, 'xt_36': 0, 'xt_34': 0, 'xt_33': 0, 'xt_31': 0, 'xt_29': 0, 'xt_28': 0, 'xt_24': 0, 'cj_ac_xt_dr_4': 0, 'xt_22': 0, 'xt_20': 0, 'xt_2': 0, 'xt_17': 0, 'xt_16': 0, 'xt_14': 0, 'xt_13': 0, 'xt_12': 0, 'xt_11': 0, 'cj_xt_dr_2': 0, 'cj_xt_dr_1': 0, '196 PAG-PPN Pax5 Sox21 Gaba': 0, '181 IC Tfap2d Maf Glut': 0, '168 SPA-SPFm-SPFp-POL-PIL-PoT Sp9 Glut': 0, '085 SI-MPO-LPO Lhx8 Gaba': 0, '102 DMH-LHA Gsx1 Gaba': 0, '101 ZI Pax6 Gaba': 0, '100 AHN Onecut3 Gaba': 0, '098 AHN-SBPV-PVHd Pdrm12 Gaba': 0, '097 PVHd-SBPV Six3 Prox1 Gaba': 0, '094 SCH Six6 Cdc14a Gaba': 0, '093 RT-ZI Gnb3 Gaba': 0, '092 TMv-PMv Tbx3 Hist-Gaba': 0, '091 ARH-PVi Six6 Dopa-Gaba': 0, '090 BST-MPN Six3 Nrgn Gaba': 0, '088 BST Tac2 Gaba': 0, '086 MPO-ADP Lhx8 Gaba': 0, '082 CEA-BST Ebf1 Pdyn Gaba': 0, '104 TU-ARH Otp Six6 Gaba': 0, '079 CEA-BST Six3 Cyp26b1 Gaba': 0, '074 MEA-BST Lhx6 Sp9 Gaba': 0, '073 MEA-BST Sox6 Gaba': 0, '072 LSX Sall3 Lmo1 Gaba': 0, '070 LSX Prdm12 Slit2 Gaba': 0, '068 LSX Otx2 Gaba': 0, '064 STR-PAL Chst9 Gaba': 0, '058 PAL-STR Gaba-Chol': 0, '057 NDB-SI-MA-STRv Lhx8 Gaba': 0, '056 Sst Chodl Gaba': 0, '054 STR Prox1 Lhx6 Gaba': 0, '041 OB-in Frmd7 Gaba': 0, '103 PVHd-DMH Lhx6 Gaba': 0, '105 TMd-DMH Foxd2 Gaba': 0, '159 IF-RL-CLI-PAG Foxa1 Glut': 0, '131 LHA-AHN-PVH Otp Trh Glut': 0, '152 RE-Xi Nox4 Glut': 0, '145 MH Tac2 Glut': 0, '143 MM-ant Foxb1 Glut': 0, '141 PH-SUM Foxa1 Glut': 0, '140 PMd-LHA Foxb1 Glut': 0, '139 PH-LHA Foxb1 Glut': 0, '138 PH Pitx2 Glut': 0, '136 PMv-TMv Pitx2 Glut': 0, '135 STN-PSTN Pitx2 Glut': 0, '134 PH-ant-LHA Otp Bsx Glut': 0, '133 PVH-SO-PVa Otp Glut': 0, '132 AHN-RCH-LHA Otp Fezf1 Glut': 0, '130 LHA Pmch Glut': 0, '106 PVpo-VMPO-MPN Hmx2 Gaba': 0, '129 VMH Nr5a1 Glut': 0, '127 DMH-LHA Vgll2 Glut': 0, '126 ARH-PVp Tbx3 Glut': 0, '125 DMH Hmx2 Glut': 0, '124 MPN-MPO-PVpo Hmx2 Glut': 0, '122 LHA-MEA Otp Glut': 0, '119 SI-MA-LPO-LHA Skor1 Glut': 0, '118 ADP-MPO Trp73 Glut': 0, '115 MS-SF Bsx Glut': 0, '111 TRS-BAC Sln Glut': 0, '108 ARH-PVp Tbx3 Gaba': 0, '107 DMH Hmx2 Gaba': 0, 'xt_m098_m104': 0}
    ss_subclass_nounlabeled_nmm_cl_v4_nn: 120 -> 122 distinct labels
    dry run — nothing written
DR: 9323 cells reverted  {'cj_ac_xt_dr_5': 2810, 'cj_ac_xt_dr_2': 2216, 'ac_dr_2': 2170, 'xt_dr_1': 1296, 'ac_xt_dr_1': 831, '339 Astrocyte-like NN': 0, 'Unlabeled': 0, 'ac_dr_1': 0, 'cj_ac_xt_dr_1': 0, 'cj_ac_xt_dr_3': 0, 'cj_ac_xt_dr_4': 0, 'cj_xt_dr_1': 0, 'cj_xt_dr_2': 0, 'dr_11': 0, 'dr_14': 0, 'dr_16': 0, 'dr_19': 0, 'dr_2': 0, 'dr_20': 0, 'dr_22': 0, 'dr_23': 0, 'dr_25': 0, 'dr_26': 0, 'dr_28': 0, 'dr_31': 0, 'dr_34': 0, 'dr_35': 0, 'dr_37': 0, 'dr_9': 0, '340 Macrophage NN': 0, '041 OB-in Frmd7 Gaba': 0, '045 OB-STR-CTX Inh IMN': 0, '337 DC NN': 0, '049 Lamp5 Gaba': 0, '054 STR Prox1 Lhx6 Gaba': 0, '056 Sst Chodl Gaba': 0, '060 OT D3 Folh1 Gaba': 0, '062 STR D2 Gaba': 0, '075 MEA-BST Lhx6 Nr2e1 Gaba': 0, '077 CEA-BST Gal Avp Gaba': 0, '086 MPO-ADP Lhx8 Gaba': 0, '091 ARH-PVi Six6 Dopa-Gaba': 0, '092 TMv-PMv Tbx3 Hist-Gaba': 0, '105 TMd-DMH Foxd2 Gaba': 0, '111 TRS-BAC Sln Glut': 0, '123 DMH Nkx2-4 Glut': 0, '130 LHA Pmch Glut': 0, '131 LHA-AHN-PVH Otp Trh Glut': 0, '133 PVH-SO-PVa Otp Glut': 0, '145 MH Tac2 Glut': 0, '314 CB Granule Glut': 0, '323 Ependymal NN': 0, '325 CHOR NN': 0, '326 OPC NN': 0, '327 Oligo NN': 0, '328 OEC NN': 0, '329 ABC NN': 0, '330 VLMC NN': 0, '331 Peri NN': 0, '333 Endo NN': 0, '338 Lymphoid NN': 0}
    ss_subclass_nounlabeled_nmm_cl_v4_nn: 61 -> 61 distinct labels
    dry run — nothing written

In [13]:
# COMMIT — overwrites the four SAM h5ads in place. Not reversible.
# Run only after the dry run above looks correct.
for S in SPECIES:
    revert_h5ad(S, H5AD[S], dry_run=False)
    gc.collect()

CJ: 1171 cells reverted  {'cj_xt_1': 504, 'cj_ac_xt_dr_5': 348, 'cj_ac_xt_dr_2': 319, '004 L6 IT CTX Glut': 0, '325 CHOR NN': 0, '231 IPN-LDT Vsx2 Nkx6-1 Glut': 0, '235 PG-TRN-LRN Fat2 Glut': 0, '277 DTN-LDT-IPN Otp Pax3 Gaba': 0, '321 Astroependymal NN': 0, '322 Tanycyte NN': 0, '323 Ependymal NN': 0, '326 OPC NN': 0, '213 SCsg Gabrr2 Gaba': 0, '327 Oligo NN': 0, '329 ABC NN': 0, '330 VLMC NN': 0, '333 Endo NN': 0, '339 Astrocyte-like NN': 0, '215 SNc-VTA-RAmb Foxa1 Dopa': 0, '211 SC Tnnt1 Gli3 Gaba': 0, '212 SCs Lef1 Gli3 Gaba': 0, 'Unlabeled': 0, '209 SCs Pax7 Nfia Gaba': 0, '208 SC Lef1 Otx2 Gaba': 0, '207 SCs Dmbx1 Gaba': 0, '205 SC-PAG Lef1 Emx2 Gaba': 0, '203 LGv-SPFp-SPFm Nkx2-2 Tcf7l2 Gaba': 0, '202 PRT Tcf7l2 Gaba': 0, '190 ND-INC Foxd2 Glut': 0, '168 SPA-SPFm-SPFp-POL-PIL-PoT Sp9 Glut': 0, '164 APN C1ql4 Glut': 0, '159 IF-RL-CLI-PAG Foxa1 Glut': 0, '153 MG-POL-SGN Nts Glut': 0, '152 RE-Xi Nox4 Glut': 0, '340 Macrophage NN': 0, 'cj_14': 0, 'cj_13': 0, '006 L4/5 IT CTX Glut': 0, 'cj_xt_dr_1': 0, 'cj_m136_m138': 0, 'cj_m091_m099': 0, 'cj_m066_m067': 0, 'cj_ac_xt_dr_4': 0, 'cj_ac_xt_dr_3': 0, 'cj_ac_xt_dr_1': 0, 'cj_ac_xt_1': 0, 'cj_ac_4': 0, 'cj_ac_3': 0, 'cj_ac_2': 0, 'cj_ac_1': 0, 'cj_9': 0, 'cj_8': 0, 'cj_5': 0, 'cj_4': 0, 'cj_37': 0, 'cj_36': 0, 'cj_34': 0, 'cj_33': 0, 'cj_32': 0, 'cj_31': 0, 'cj_29': 0, 'cj_28': 0, 'cj_27': 0, 'cj_22': 0, 'cj_21': 0, 'cj_19': 0, 'cj_18': 0, '149 PVT-PT Ntrk1 Glut': 0, '145 MH Tac2 Glut': 0, '141 PH-SUM Foxa1 Glut': 0, '064 STR-PAL Chst9 Gaba': 0, '092 TMv-PMv Tbx3 Hist-Gaba': 0, '090 BST-MPN Six3 Nrgn Gaba': 0, '089 PVR Six3 Sox3 Gaba': 0, '088 BST Tac2 Gaba': 0, '086 MPO-ADP Lhx8 Gaba': 0, '085 SI-MPO-LPO Lhx8 Gaba': 0, '082 CEA-BST Ebf1 Pdyn Gaba': 0, '081 ACB-BST-FS D1 Gaba': 0, '076 MEA-BST Lhx6 Nfib Gaba': 0, '074 MEA-BST Lhx6 Sp9 Gaba': 0, '070 LSX Prdm12 Slit2 Gaba': 0, '069 LSX Nkx2-1 Gaba': 0, '068 LSX Otx2 Gaba': 0, '067 LSX Sall3 Pax6 Gaba': 0, '063 STR D1 Sema5a Gaba': 0, '094 SCH Six6 Cdc14a Gaba': 0, '062 STR D2 Gaba': 0, '061 STR D1 Gaba': 0, '058 PAL-STR Gaba-Chol': 0, '057 NDB-SI-MA-STRv Lhx8 Gaba': 0, '055 STR Lhx8 Gaba': 0, '054 STR Prox1 Lhx6 Gaba': 0, '053 Sst Gaba': 0, '052 Pvalb Gaba': 0, '049 Lamp5 Gaba': 0, '041 OB-in Frmd7 Gaba': 0, '017 CA3 Glut': 0, '014 LA-BLA-BMA-PA Glut': 0, '013 COAp Grxcr2 Glut': 0, '007 L2/3 IT CTX Glut': 0, '093 RT-ZI Gnb3 Gaba': 0, '097 PVHd-SBPV Six3 Prox1 Gaba': 0, '140 PMd-LHA Foxb1 Glut': 0, '123 DMH Nkx2-4 Glut': 0, '138 PH Pitx2 Glut': 0, '136 PMv-TMv Pitx2 Glut': 0, '135 STN-PSTN Pitx2 Glut': 0, '134 PH-ant-LHA Otp Bsx Glut': 0, '133 PVH-SO-PVa Otp Glut': 0, '132 AHN-RCH-LHA Otp Fezf1 Glut': 0, '131 LHA-AHN-PVH Otp Trh Glut': 0, '130 LHA Pmch Glut': 0, '129 VMH Nr5a1 Glut': 0, '128 VMH Fezf1 Glut': 0, '127 DMH-LHA Vgll2 Glut': 0, '126 ARH-PVp Tbx3 Glut': 0, '125 DMH Hmx2 Glut': 0, '124 MPN-MPO-PVpo Hmx2 Glut': 0, '122 LHA-MEA Otp Glut': 0, '098 AHN-SBPV-PVHd Pdrm12 Gaba': 0, '119 SI-MA-LPO-LHA Skor1 Glut': 0, '118 ADP-MPO Trp73 Glut': 0, '117 LHA Barhl2 Glut': 0, '116 AVPV-MEPO-SFO Tbr1 Glut': 0, '115 MS-SF Bsx Glut': 0, '111 TRS-BAC Sln Glut': 0, '109 LGv-ZI Otx2 Gaba': 0, '108 ARH-PVp Tbx3 Gaba': 0, '107 DMH Hmx2 Gaba': 0, '106 PVpo-VMPO-MPN Hmx2 Gaba': 0, '104 TU-ARH Otp Six6 Gaba': 0, '102 DMH-LHA Gsx1 Gaba': 0, '101 ZI Pax6 Gaba': 0, '100 AHN Onecut3 Gaba': 0, 'cj_xt_dr_2': 0}
    ss_subclass_nounlabeled_nmm_cl_v4_nn: 136 -> 137 distinct labels
    saved ss_subclass_nounlabeled_nmm_cl_v4_nn into Active_SAM_joined/SAM_CJ_joined_v2_cleaned_03122025.h5ad
AC: 1592 cells reverted  {'cj_ac_xt_dr_2': 561, 'cj_ac_xt_dr_5': 513, 'ac_dr_2': 398, 'ac_xt_dr_1': 120, '333 Endo NN': 0, '338 Lymphoid NN': 0, '330 VLMC NN': 0, '329 ABC NN': 0, '327 Oligo NN': 0, '231 IPN-LDT Vsx2 Nkx6-1 Glut': 0, '325 CHOR NN': 0, '324 Hypendymal NN': 0, '323 Ependymal NN': 0, '322 Tanycyte NN': 0, '321 Astroependymal NN': 0, '277 DTN-LDT-IPN Otp Pax3 Gaba': 0, '326 OPC NN': 0, '215 SNc-VTA-RAmb Foxa1 Dopa': 0, '216 MB-MY Tph2 Glut-Sero': 0, '340 Macrophage NN': 0, '214 IPN Otp Crisp1 Gaba': 0, '213 SCsg Gabrr2 Gaba': 0, '212 SCs Lef1 Gli3 Gaba': 0, '211 SC Tnnt1 Gli3 Gaba': 0, '209 SCs Pax7 Nfia Gaba': 0, '208 SC Lef1 Otx2 Gaba': 0, '205 SC-PAG Lef1 Emx2 Gaba': 0, '204 SC Otx2 Gcnt4 Gaba': 0, '203 LGv-SPFp-SPFm Nkx2-2 Tcf7l2 Gaba': 0, '200 PAG-ND-PCG Onecut1 Gaba': 0, '196 PAG-PPN Pax5 Sox21 Gaba': 0, '188 SCop Sln Glut': 0, '339 Astrocyte-like NN': 0, 'ac_14': 0, 'Unlabeled': 0, 'ac_m136_m138': 0, 'cj_ac_xt_dr_4': 0, 'cj_ac_xt_dr_3': 0, 'cj_ac_xt_dr_1': 0, 'cj_ac_xt_1': 0, 'cj_ac_4': 0, 'cj_ac_3': 0, 'cj_ac_2': 0, 'cj_ac_1': 0, 'ac_xt_4': 0, 'ac_xt_3': 0, 'ac_xt_2': 0, 'ac_xt_1': 0, 'ac_m124_m130': 0, '186 SCop Pou4f2 Neurod2 Glut': 0, 'ac_m058_m086': 0, 'ac_dr_1': 0, 'ac_35': 0, 'ac_32': 0, 'ac_31': 0, 'ac_29': 0, 'ac_28': 0, 'ac_26': 0, 'ac_25': 0, 'ac_2': 0, 'ac_19': 0, 'ac_18': 0, '187 SCsg Pde5a Glut': 0, '013 COAp Grxcr2 Glut': 0, '018 L2 IT PPP-APr Glut': 0, '070 LSX Prdm12 Slit2 Gaba': 0, '099 SBPV-PVa Six6 Satb2 Gaba': 0, '098 AHN-SBPV-PVHd Pdrm12 Gaba': 0, '097 PVHd-SBPV Six3 Prox1 Gaba': 0, '094 SCH Six6 Cdc14a Gaba': 0, '093 RT-ZI Gnb3 Gaba': 0, '092 TMv-PMv Tbx3 Hist-Gaba': 0, '089 PVR Six3 Sox3 Gaba': 0, '086 MPO-ADP Lhx8 Gaba': 0, '085 SI-MPO-LPO Lhx8 Gaba': 0, '079 CEA-BST Six3 Cyp26b1 Gaba': 0, '076 MEA-BST Lhx6 Nfib Gaba': 0, '074 MEA-BST Lhx6 Sp9 Gaba': 0, '073 MEA-BST Sox6 Gaba': 0, '069 LSX Nkx2-1 Gaba': 0, '101 ZI Pax6 Gaba': 0, '068 LSX Otx2 Gaba': 0, '067 LSX Sall3 Pax6 Gaba': 0, '064 STR-PAL Chst9 Gaba': 0, '062 STR D2 Gaba': 0, '061 STR D1 Gaba': 0, '058 PAL-STR Gaba-Chol': 0, '057 NDB-SI-MA-STRv Lhx8 Gaba': 0, '056 Sst Chodl Gaba': 0, '055 STR Lhx8 Gaba': 0, '054 STR Prox1 Lhx6 Gaba': 0, '047 Sncg Gaba': 0, '039 OB Meis2 Thsd7b Gaba': 0, '022 L5 ET CTX Glut': 0, '100 AHN Onecut3 Gaba': 0, '104 TU-ARH Otp Six6 Gaba': 0, '168 SPA-SPFm-SPFp-POL-PIL-PoT Sp9 Glut': 0, '129 VMH Nr5a1 Glut': 0, '152 RE-Xi Nox4 Glut': 0, '151 TH Prkcd Grin2c Glut': 0, '149 PVT-PT Ntrk1 Glut': 0, '142 HY Gnrh1 Glut': 0, '141 PH-SUM Foxa1 Glut': 0, '140 PMd-LHA Foxb1 Glut': 0, '136 PMv-TMv Pitx2 Glut': 0, '135 STN-PSTN Pitx2 Glut': 0, '134 PH-ant-LHA Otp Bsx Glut': 0, '133 PVH-SO-PVa Otp Glut': 0, '132 AHN-RCH-LHA Otp Fezf1 Glut': 0, '131 LHA-AHN-PVH Otp Trh Glut': 0, '130 LHA Pmch Glut': 0, '128 VMH Fezf1 Glut': 0, '106 PVpo-VMPO-MPN Hmx2 Gaba': 0, '127 DMH-LHA Vgll2 Glut': 0, '126 ARH-PVp Tbx3 Glut': 0, '125 DMH Hmx2 Glut': 0, '123 DMH Nkx2-4 Glut': 0, '122 LHA-MEA Otp Glut': 0, '119 SI-MA-LPO-LHA Skor1 Glut': 0, '118 ADP-MPO Trp73 Glut': 0, '117 LHA Barhl2 Glut': 0, '116 AVPV-MEPO-SFO Tbr1 Glut': 0, '115 MS-SF Bsx Glut': 0, '111 TRS-BAC Sln Glut': 0, '109 LGv-ZI Otx2 Gaba': 0, '107 DMH Hmx2 Gaba': 0, '175 SC Bnc2 Glut': 0}
    ss_subclass_nounlabeled_nmm_cl_v4_nn: 127 -> 127 distinct labels
    saved ss_subclass_nounlabeled_nmm_cl_v4_nn into Active_SAM_joined/SAM_AC_ncbi_soupx_cleaned_03122025.h5ad
XT: 1716 cells reverted  {'cj_ac_xt_dr_2': 813, 'xt_dr_1': 429, 'cj_xt_1': 217, 'cj_ac_xt_dr_5': 142, 'ac_xt_dr_1': 115, '330 VLMC NN': 0, 'cj_ac_xt_1': 0, 'ac_xt_4': 0, 'ac_xt_3': 0, 'ac_xt_2': 0, 'ac_xt_1': 0, 'Unlabeled': 0, '340 Macrophage NN': 0, '339 Astrocyte-like NN': 0, '338 Lymphoid NN': 0, '333 Endo NN': 0, '009 L2/3 IT PIR-ENTl Glut': 0, 'cj_ac_xt_dr_1': 0, '327 Oligo NN': 0, '326 OPC NN': 0, '322 Tanycyte NN': 0, '277 DTN-LDT-IPN Otp Pax3 Gaba': 0, '275 PDTg Otp Olig3 Gaba': 0, '262 Pineal Crx Glut': 0, '232 LDT Vsx2 Nkx6-1 Nfib Glut': 0, '231 IPN-LDT Vsx2 Nkx6-1 Glut': 0, '230 PRNr Otp Nfib Glut': 0, '216 MB-MY Tph2 Glut-Sero': 0, '215 SNc-VTA-RAmb Foxa1 Dopa': 0, '214 IPN Otp Crisp1 Gaba': 0, '209 SCs Pax7 Nfia Gaba': 0, '329 ABC NN': 0, 'cj_ac_xt_dr_3': 0, '011 L2 IT ENT-po Glut': 0, 'xt_25': 0, 'xt_8': 0, 'xt_7': 0, 'xt_42': 0, 'xt_41': 0, 'xt_40': 0, 'xt_36': 0, 'xt_34': 0, 'xt_33': 0, 'xt_31': 0, 'xt_29': 0, 'xt_28': 0, 'xt_24': 0, 'cj_ac_xt_dr_4': 0, 'xt_22': 0, 'xt_20': 0, 'xt_2': 0, 'xt_17': 0, 'xt_16': 0, 'xt_14': 0, 'xt_13': 0, 'xt_12': 0, 'xt_11': 0, 'cj_xt_dr_2': 0, 'cj_xt_dr_1': 0, '196 PAG-PPN Pax5 Sox21 Gaba': 0, '181 IC Tfap2d Maf Glut': 0, '168 SPA-SPFm-SPFp-POL-PIL-PoT Sp9 Glut': 0, '085 SI-MPO-LPO Lhx8 Gaba': 0, '102 DMH-LHA Gsx1 Gaba': 0, '101 ZI Pax6 Gaba': 0, '100 AHN Onecut3 Gaba': 0, '098 AHN-SBPV-PVHd Pdrm12 Gaba': 0, '097 PVHd-SBPV Six3 Prox1 Gaba': 0, '094 SCH Six6 Cdc14a Gaba': 0, '093 RT-ZI Gnb3 Gaba': 0, '092 TMv-PMv Tbx3 Hist-Gaba': 0, '091 ARH-PVi Six6 Dopa-Gaba': 0, '090 BST-MPN Six3 Nrgn Gaba': 0, '088 BST Tac2 Gaba': 0, '086 MPO-ADP Lhx8 Gaba': 0, '082 CEA-BST Ebf1 Pdyn Gaba': 0, '104 TU-ARH Otp Six6 Gaba': 0, '079 CEA-BST Six3 Cyp26b1 Gaba': 0, '074 MEA-BST Lhx6 Sp9 Gaba': 0, '073 MEA-BST Sox6 Gaba': 0, '072 LSX Sall3 Lmo1 Gaba': 0, '070 LSX Prdm12 Slit2 Gaba': 0, '068 LSX Otx2 Gaba': 0, '064 STR-PAL Chst9 Gaba': 0, '058 PAL-STR Gaba-Chol': 0, '057 NDB-SI-MA-STRv Lhx8 Gaba': 0, '056 Sst Chodl Gaba': 0, '054 STR Prox1 Lhx6 Gaba': 0, '041 OB-in Frmd7 Gaba': 0, '103 PVHd-DMH Lhx6 Gaba': 0, '105 TMd-DMH Foxd2 Gaba': 0, '159 IF-RL-CLI-PAG Foxa1 Glut': 0, '131 LHA-AHN-PVH Otp Trh Glut': 0, '152 RE-Xi Nox4 Glut': 0, '145 MH Tac2 Glut': 0, '143 MM-ant Foxb1 Glut': 0, '141 PH-SUM Foxa1 Glut': 0, '140 PMd-LHA Foxb1 Glut': 0, '139 PH-LHA Foxb1 Glut': 0, '138 PH Pitx2 Glut': 0, '136 PMv-TMv Pitx2 Glut': 0, '135 STN-PSTN Pitx2 Glut': 0, '134 PH-ant-LHA Otp Bsx Glut': 0, '133 PVH-SO-PVa Otp Glut': 0, '132 AHN-RCH-LHA Otp Fezf1 Glut': 0, '130 LHA Pmch Glut': 0, '106 PVpo-VMPO-MPN Hmx2 Gaba': 0, '129 VMH Nr5a1 Glut': 0, '127 DMH-LHA Vgll2 Glut': 0, '126 ARH-PVp Tbx3 Glut': 0, '125 DMH Hmx2 Glut': 0, '124 MPN-MPO-PVpo Hmx2 Glut': 0, '122 LHA-MEA Otp Glut': 0, '119 SI-MA-LPO-LHA Skor1 Glut': 0, '118 ADP-MPO Trp73 Glut': 0, '115 MS-SF Bsx Glut': 0, '111 TRS-BAC Sln Glut': 0, '108 ARH-PVp Tbx3 Gaba': 0, '107 DMH Hmx2 Gaba': 0, 'xt_m098_m104': 0}
    ss_subclass_nounlabeled_nmm_cl_v4_nn: 120 -> 122 distinct labels
    saved ss_subclass_nounlabeled_nmm_cl_v4_nn into Active_SAM_joined/SAM_XT_joined_Slc17a6_cleaned_03122205.h5ad
DR: 9323 cells reverted  {'cj_ac_xt_dr_5': 2810, 'cj_ac_xt_dr_2': 2216, 'ac_dr_2': 2170, 'xt_dr_1': 1296, 'ac_xt_dr_1': 831, '339 Astrocyte-like NN': 0, 'Unlabeled': 0, 'ac_dr_1': 0, 'cj_ac_xt_dr_1': 0, 'cj_ac_xt_dr_3': 0, 'cj_ac_xt_dr_4': 0, 'cj_xt_dr_1': 0, 'cj_xt_dr_2': 0, 'dr_11': 0, 'dr_14': 0, 'dr_16': 0, 'dr_19': 0, 'dr_2': 0, 'dr_20': 0, 'dr_22': 0, 'dr_23': 0, 'dr_25': 0, 'dr_26': 0, 'dr_28': 0, 'dr_31': 0, 'dr_34': 0, 'dr_35': 0, 'dr_37': 0, 'dr_9': 0, '340 Macrophage NN': 0, '041 OB-in Frmd7 Gaba': 0, '045 OB-STR-CTX Inh IMN': 0, '337 DC NN': 0, '049 Lamp5 Gaba': 0, '054 STR Prox1 Lhx6 Gaba': 0, '056 Sst Chodl Gaba': 0, '060 OT D3 Folh1 Gaba': 0, '062 STR D2 Gaba': 0, '075 MEA-BST Lhx6 Nr2e1 Gaba': 0, '077 CEA-BST Gal Avp Gaba': 0, '086 MPO-ADP Lhx8 Gaba': 0, '091 ARH-PVi Six6 Dopa-Gaba': 0, '092 TMv-PMv Tbx3 Hist-Gaba': 0, '105 TMd-DMH Foxd2 Gaba': 0, '111 TRS-BAC Sln Glut': 0, '123 DMH Nkx2-4 Glut': 0, '130 LHA Pmch Glut': 0, '131 LHA-AHN-PVH Otp Trh Glut': 0, '133 PVH-SO-PVa Otp Glut': 0, '145 MH Tac2 Glut': 0, '314 CB Granule Glut': 0, '323 Ependymal NN': 0, '325 CHOR NN': 0, '326 OPC NN': 0, '327 Oligo NN': 0, '328 OEC NN': 0, '329 ABC NN': 0, '330 VLMC NN': 0, '331 Peri NN': 0, '333 Endo NN': 0, '338 Lymphoid NN': 0}
    ss_subclass_nounlabeled_nmm_cl_v4_nn: 61 -> 61 distinct labels
    saved ss_subclass_nounlabeled_nmm_cl_v4_nn into Active_SAM_joined/SAM_DR_ncbi_joined_cleaned_07172026.h5ad