In [9]:
sam1=SAM()
sam1.load_data('Active_SAM_joined/SAM_CJ_joined_v2_cleaned_03122025.h5ad')

In [10]:
!pip install anndata==0.8.0

Requirement already satisfied: anndata==0.8.0 in /scratch/miniconda/lib/python3.7/site-packages (0.8.0)
Requirement already satisfied: h5py>=3 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (3.8.0)
Requirement already satisfied: typing_extensions in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (4.7.1)
Requirement already satisfied: scipy>1.4 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (1.7.3)
Requirement already satisfied: importlib_metadata>=0.7 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (4.11.4)
Requirement already satisfied: pandas>=1.1.1 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (1.3.5)
Requirement already satisfied: numpy>=1.16.5 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (1.21.6)
Requirement already satisfied: packaging>=20 in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (21.3)
Requirement already satisfied: natsort in /scratch/miniconda/lib/python3.7/site-packages (from anndata==0.8.0) (8.1.0)
Requirement already satisfied: zipp>=0.5 in /scratch/miniconda/lib/python3.7/site-packages (from importlib_metadata>=0.7->anndata==0.8.0) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /scratch/miniconda/lib/python3.7/site-packages (from packaging>=20->anndata==0.8.0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /scratch/miniconda/lib/python3.7/site-packages (from pandas>=1.1.1->anndata==0.8.0) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /scratch/miniconda/lib/python3.7/site-packages (from pandas>=1.1.1->anndata==0.8.0) (2022.1)
Requirement already satisfied: six>=1.5 in /scratch/miniconda/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=1.1.1->anndata==0.8.0) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [11]:
!pip install loompy

Requirement already satisfied: loompy in /scratch/miniconda/lib/python3.7/site-packages (3.0.8)
Requirement already satisfied: numpy-groupies in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (0.9.22)
Requirement already satisfied: h5py in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (3.8.0)
Requirement already satisfied: numpy in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (1.21.6)
Requirement already satisfied: click in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (8.1.8)
Requirement already satisfied: scipy in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (1.7.3)
Requirement already satisfied: setuptools in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (62.6.0)
Requirement already satisfied: numba in /scratch/miniconda/lib/python3.7/site-packages (from loompy) (0.52.0)
Requirement already satisfied: importlib-metadata in /scratch/miniconda/lib/python3.7/site-packages (from click->loompy) (4.11.4)
Requirement already satisfied: llvmlite<0.36,>=0.35.0 in /scratch/miniconda/lib/python3.7/site-packages (from numba->loompy) (0.35.0)
Requirement already satisfied: zipp>=0.5 in /scratch/miniconda/lib/python3.7/site-packages (from importlib-metadata->click->loompy) (3.8.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /scratch/miniconda/lib/python3.7/site-packages (from importlib-metadata->click->loompy) (4.7.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [12]:
from samalg import SAM
import scanpy as sc
import statistics
import matplotlib.pyplot as plt
import seaborn as sns
import random
import pandas as pd
import matplotlib.colors
import scipy
import numpy as np
import sklearn.metrics as metrics
from scipy import sparse
from samap.mapping import SAMAP
from samap.analysis import (get_mapping_scores, GenePairFinder, transfer_annotations,
                            sankey_plot, chord_plot, CellTypeTriangles, 
                            ParalogSubstitutions, FunctionalEnrichment,
                            convert_eggnog_to_homologs, GeneTriangles)
from samalg import SAM
import pandas as pd
from Bio import SeqIO
from samap.utils import (save_samap, load_samap)
import scanpy as sc
import loompy

In [13]:
sam1.adata.obs

,orig.ident,nCount_RNA,nFeature_RNA,n_genes,n_counts,key,hicat_merged,subclass_id_label_mapping,subclass_id_label_lc,leiden_clusters,...,eq_subclass_nounlabeled_NN,eq_subclass_nounlabeled_nmm,ss_subclass,ss_subclass_nounlabeled,ss_class,ss_subclass_nounlabeled_astro,ss_subclass_v2,ss_subclass_v2_nounlabeled,ss_subclass_nounlabeled_nmm,ss_subclass_v3_nounlabeled
AAACCCAAGACGACTG Run 11 sample 8,CJ,1455.0,797,797,1455.0,Run 11 sample 8,341,085 SI-MPO-LPO Lhx8 Gaba,362,90,...,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,11 CNU-HYa GABA,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba
AAACCCAAGTGCTCAT Run 11 sample 8,CJ,1576.0,728,728,1576.0,Run 11 sample 8,25,Unlabeled,33,41,...,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,31 OPC-Oligo,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN
AAACCCAGTCGAAACG Run 11 sample 8,CJ,1489.0,763,763,1489.0,Run 11 sample 8,152,128 VMH Fezf1 Glut,496,23,...,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,14 HY Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut
AAACCCAGTCTTGAAC Run 11 sample 8,CJ,797.0,521,521,797.0,Run 11 sample 8,53,Unlabeled,598,2,...,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,31 OPC-Oligo,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN
AAACCCAGTGCCGGTT Run 11 sample 8,CJ,1874.0,951,951,1874.0,Run 11 sample 8,230,090 BST-MPN Six3 Nrgn Gaba,501,25,...,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,11 CNU-HYa GABA,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTTCCACAGCG Run 11 sample 7,CJ,6076.0,2117,2117,6076.0,Run 11 sample 7,571,125 DMH Hmx2 Glut,113,29,...,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,14 HY Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut
TTTGGTTTCCATCAGA Run 11 sample 7,CJ,13270.0,3222,3222,13270.0,Run 11 sample 7,277,132 AHN-RCH-LHA Otp Fezf1 Glut,25,85,...,cj_36,cj_xt_5,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,14 HY Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut
TTTGGTTTCGGTGCAC Run 11 sample 7,CJ,7299.0,2248,2248,7299.0,Run 11 sample 7,152,129 VMH Nr5a1 Glut,93,21,...,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,14 HY Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut
TTTGTTGAGGAATTAC Run 11 sample 7,CJ,8517.0,2544,2544,8517.0,Run 11 sample 7,1122,057 NDB-SI-MA-STRv Lhx8 Gaba,75,30,...,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,08 CNU-MGE GABA,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba
TTTGTTGTCTGAGAAA Run 11 sample 7,CJ,2774.0,1221,1221,2774.0,Run 11 sample 7,53,Unlabeled,60,41,...,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,31 OPC-Oligo,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN

In [14]:
sam1.adata.obs = sam1.adata.obs.drop(['subclass_id_label_mapping','subclass_id_label_lc','leiden_clusters','subclass_id_label_mapping_nounlabeled','neurotransmitter','region_label','subclass_id_label_reduced_mapping','subclass_id_label_reduced_lc','subclass_id_label_reduced_mapping_nounlabeled'], axis = 1)

In [15]:
sam1.adata.obs

,orig.ident,nCount_RNA,nFeature_RNA,n_genes,n_counts,key,hicat_merged,fraction_match,best_match,frac_match_test,...,eq_subclass_nounlabeled_NN,eq_subclass_nounlabeled_nmm,ss_subclass,ss_subclass_nounlabeled,ss_class,ss_subclass_nounlabeled_astro,ss_subclass_v2,ss_subclass_v2_nounlabeled,ss_subclass_nounlabeled_nmm,ss_subclass_v3_nounlabeled
AAACCCAAGACGACTG Run 11 sample 8,CJ,1455.0,797,797,1455.0,Run 11 sample 8,341,1.0,085 SI-MPO-LPO Lhx8 Gaba,1.0,...,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,11 CNU-HYa GABA,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba
AAACCCAAGTGCTCAT Run 11 sample 8,CJ,1576.0,728,728,1576.0,Run 11 sample 8,25,1.0,327 Oligo NN,1.0,...,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,31 OPC-Oligo,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN
AAACCCAGTCGAAACG Run 11 sample 8,CJ,1489.0,763,763,1489.0,Run 11 sample 8,152,1.0,Unlabeled,0.0,...,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,14 HY Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut
AAACCCAGTCTTGAAC Run 11 sample 8,CJ,797.0,521,521,797.0,Run 11 sample 8,53,1.0,327 Oligo NN,1.0,...,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,31 OPC-Oligo,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN
AAACCCAGTGCCGGTT Run 11 sample 8,CJ,1874.0,951,951,1874.0,Run 11 sample 8,230,1.0,090 BST-MPN Six3 Nrgn Gaba,1.0,...,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,11 CNU-HYa GABA,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTTCCACAGCG Run 11 sample 7,CJ,6076.0,2117,2117,6076.0,Run 11 sample 7,571,0.7,125 DMH Hmx2 Glut,0.7,...,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,14 HY Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut
TTTGGTTTCCATCAGA Run 11 sample 7,CJ,13270.0,3222,3222,13270.0,Run 11 sample 7,277,0.4,131 LHA-AHN-PVH Otp Trh Glut,0.4,...,cj_36,cj_xt_5,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,14 HY Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut
TTTGGTTTCGGTGCAC Run 11 sample 7,CJ,7299.0,2248,2248,7299.0,Run 11 sample 7,152,0.9,Unlabeled,0.0,...,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,14 HY Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut
TTTGTTGAGGAATTAC Run 11 sample 7,CJ,8517.0,2544,2544,8517.0,Run 11 sample 7,1122,1.0,057 NDB-SI-MA-STRv Lhx8 Gaba,1.0,...,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,08 CNU-MGE GABA,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba
TTTGTTGTCTGAGAAA Run 11 sample 7,CJ,2774.0,1221,1221,2774.0,Run 11 sample 7,53,1.0,327 Oligo NN,1.0,...,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,31 OPC-Oligo,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN

In [16]:
sam1.adata.obs = sam1.adata.obs.drop(['hicat_merged','fraction_match','best_match','frac_match_test','leiden_removal','nCount_SCT','nFeature_SCT','SCT_snn_res.0.8','seurat_clusters'],axis = 1)

In [17]:
sam1.adata.obs

,orig.ident,nCount_RNA,nFeature_RNA,n_genes,n_counts,key,SCT_snn_res.5,eq_subclass,eq_subclass_lc,eq_subclass_frac,...,eq_subclass_nounlabeled_NN,eq_subclass_nounlabeled_nmm,ss_subclass,ss_subclass_nounlabeled,ss_class,ss_subclass_nounlabeled_astro,ss_subclass_v2,ss_subclass_v2_nounlabeled,ss_subclass_nounlabeled_nmm,ss_subclass_v3_nounlabeled
AAACCCAAGACGACTG Run 11 sample 8,CJ,1455.0,797,797,1455.0,Run 11 sample 8,31,085 SI-MPO-LPO Lhx8 Gaba,170,1.000000,...,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,11 CNU-HYa GABA,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba,085 SI-MPO-LPO Lhx8 Gaba
AAACCCAAGTGCTCAT Run 11 sample 8,CJ,1576.0,728,728,1576.0,Run 11 sample 8,16,327 Oligo NN,81,1.000000,...,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,31 OPC-Oligo,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN
AAACCCAGTCGAAACG Run 11 sample 8,CJ,1489.0,763,763,1489.0,Run 11 sample 8,21,128 VMH Fezf1 Glut,23,0.966667,...,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,14 HY Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut,128 VMH Fezf1 Glut
AAACCCAGTCTTGAAC Run 11 sample 8,CJ,797.0,521,521,797.0,Run 11 sample 8,10,327 Oligo NN,292,1.000000,...,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,31 OPC-Oligo,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN
AAACCCAGTGCCGGTT Run 11 sample 8,CJ,1874.0,951,951,1874.0,Run 11 sample 8,33,090 BST-MPN Six3 Nrgn Gaba,84,1.000000,...,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,11 CNU-HYa GABA,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba,090 BST-MPN Six3 Nrgn Gaba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTTCCACAGCG Run 11 sample 7,CJ,6076.0,2117,2117,6076.0,Run 11 sample 7,62,125 DMH Hmx2 Glut,135,1.000000,...,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,14 HY Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut,125 DMH Hmx2 Glut
TTTGGTTTCCATCAGA Run 11 sample 7,CJ,13270.0,3222,3222,13270.0,Run 11 sample 7,73,Unlabeled,72,1.000000,...,cj_36,cj_xt_5,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,14 HY Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut,131 LHA-AHN-PVH Otp Trh Glut
TTTGGTTTCGGTGCAC Run 11 sample 7,CJ,7299.0,2248,2248,7299.0,Run 11 sample 7,14,129 VMH Nr5a1 Glut,174,1.000000,...,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,14 HY Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut,129 VMH Nr5a1 Glut
TTTGTTGAGGAATTAC Run 11 sample 7,CJ,8517.0,2544,2544,8517.0,Run 11 sample 7,47,057 NDB-SI-MA-STRv Lhx8 Gaba,67,1.000000,...,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,08 CNU-MGE GABA,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba,057 NDB-SI-MA-STRv Lhx8 Gaba
TTTGTTGTCTGAGAAA Run 11 sample 7,CJ,2774.0,1221,1221,2774.0,Run 11 sample 7,16,327 Oligo NN,28,1.000000,...,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,31 OPC-Oligo,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN,327 Oligo NN

In [19]:
for i in range(1,30):
    dat = sc.read_loom('Subclustering/subset_Allen_institute_Full_cluster_30_' + str(i) + '.loom')
    dat.obs_names = dat.obs['obs_names']
    dat.var_names = list(dat.var['x'])
    
    sam=SAM(dat)
    sam.preprocess_data()
    sam.run()
    
    sam.adata.obs_names_make_unique()
    sam.adata.var_names_make_unique()

    sam1.adata.obs_names_make_unique()
    sam1.adata.var_names_make_unique()
    
    sams = {'mg':sam,'cj':sam1}

    sm = SAMAP(
        sams,
        f_maps = 'BLASTMAPPING/maps/active_maps/',
    )
    
    sm.run(pairwise=True)
    
    save_samap(sm , 'Active_SAMap_Joined/sm_Allen_Full_cj_v2_cleaned_03122025_cluster_30_' + str(i) + '.pkl')

OSError: File 'Subclustering/subset_Allen_institute_Full_cluster_30_1.loom' not found